# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

variables:
- group: release-variables

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $(BuildTarget)
  displayName: 'Run a one-line script'

- script: |
    echo $(BuildTarget)
  displayName: 'Run a multi-line script'


